env: "local" # local, dev, prod
http_server:
  address: "localhost:8083"
  timeout: 4s
  idle_timeout: 60s
  user: "myuser"
  password: "mypass"
database_credentials:
    host: "localhost"
    port: 5432
    name: "test"